@echo off

echo Windows 7 OEM Activation Installing
echo Please wait...
echo.

SET RC=%Windir%\System32\reg.exe
IF EXIST %Windir%\Sysnative\reg.exe SET RC=%Windir%\Sysnative\reg.exe
SET RQR=%RC% QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v "EditionID" 
SET INL=IF NOT ERRORLEVEL 1 

::manufacturer brand check/set::
cscript //nologo Bios\Bios.vbs | findstr /I "ACER AcerSystem TravelMate" >nul
%INL% SET MAN=ACER&GOTO:ACER
cscript //nologo Bios\Bios.vbs | findstr /I "DSGLTD ADVENT" >nul
%INL% SET MAN=ADVENT&GOTO:ADVENT
cscript //nologo Bios\Bios.vbs | findstr /I "ALWARE ALIENWARE" >nul
%INL% SET MAN=ALIENWARE&GOTO:ALIENWARE
cscript //nologo Bios\Bios.vbs | findstr /I "_ASUS_ ASUS_FLASH ASUS ASUSTeK" >nul
%INL% SET MAN=ASUS&GOTO:ASUS
cscript //nologo Bios\Bios.vbs | findstr /I "AQUARI AQUARIUS" >nul
%INL% SET MAN=AQUARIUS&GOTO:AQUARIUS
cscript //nologo Bios\Bios.vbs | findstr /I "BenQ BenQHub" >nul
%INL% SET MAN=BENQ&GOTO:BENQ
cscript //nologo Bios\Bios.vbs | findstr /I "CASPER" >nul
%INL% SET MAN=CASPER&GOTO:CASPER
cscript //nologo Bios\Bios.vbs | findstr /I "COMPAQ" >nul
%INL% SET MAN=COMPAQ&GOTO:COMPAQ
cscript //nologo Bios\Bios.vbs | findstr /I "DELL" >nul
%INL% SET MAN=DELL&GOTO:DELL
cscript //nologo Bios\Bios.vbs | findstr /I "XPS" >nul
%INL% SET MAN=DELLXPS&GOTO:DELL
cscript //nologo Bios\Bios.vbs | findstr /I "Dealin" >nul
%INL% SET MAN=DEALIN&GOTO:DEALIN
cscript //nologo Bios\Bios.vbs | findstr /I "Exc ECS ELITEGROUP ELITE" >nul
%INL% SET MAN=ECS&GOTO:ECS
cscript //nologo Bios\Bios.vbs | findstr /I "EMACHINES" >nul
%INL% SET MAN=EMACHINES&GOTO:ACER
cscript //nologo Bios\Bios.vbs | findstr /I "Datate EXPER" >nul
%INL% SET MAN=EXPER&GOTO:EXPER
cscript //nologo Bios\Bios.vbs | findstr /I "FOUNDR FOUNDER" >nul
%INL% SET MAN=FOUNDER&GOTO:FOUNDER
cscript //nologo Bios\Bios.vbs | findstr /I "FSC SIEMENS" >nul
%INL% SET MAN=FSC&GOTO:FSC
cscript //nologo Bios\Bios.vbs | findstr /I "FUJ FUJITSU FUJITSU-PC" >nul
%INL% SET MAN=FUJITSU&GOTO:FUJITSU
cscript //nologo Bios\Bios.vbs | findstr /I "GATEWAY Gatewa" >nul
%INL% SET MAN=GATEWAY&GOTO:ACER
cscript //nologo Bios\Bios.vbs | findstr /I "GBT GIGABYTE" >nul
%INL% SET MAN=GIGABYTE&GOTO:GIGABYTE
cscript //nologo Bios\Bios.vbs | findstr /I "cgwall GREATWALL" >nul
%INL% SET MAN=GWALL&GOTO:GWALL
cscript //nologo Bios\Bios.vbs | findstr /I "haier HaierComputer" >nul
%INL% SET MAN=HAIER&GOTO:HAIER
cscript //nologo Bios\Bios.vbs | findstr /I "HSPW07 HANNSPREE" >nul
%INL% SET MAN=HANNSPREE&GOTO:HANNSPREE
cscript //nologo Bios\Bios.vbs | findstr /I "HASEE HASEECOMPUTER" >nul
%INL% SET MAN=HASEE&GOTO:HASEE
cscript //nologo Bios\Bios.vbs | findstr /I "HCLINF HCL" >nul
%INL% SET MAN=HCL&GOTO:HCL
cscript //nologo Bios\Bios.vbs | findstr /I "HEWLETT Hewlett-P Hewlett-Packard" >nul
%INL% SET MAN=HP&GOTO:HP
cscript //nologo Bios\Bios.vbs | findstr /I "higrad HIGRADE HIGRADED" >nul
%INL% SET MAN=HIGRADE&GOTO:HIGRADE
cscript //nologo Bios\Bios.vbs | findstr /I "HYRSLP HYRICAN HYRICAN_AG" >nul
%INL% SET MAN=HYRICAN&GOTO:HYRICAN
cscript //nologo Bios\Bios.vbs | findstr /I "JOOYON JOOYONTECH" >nul
%INL% SET MAN=JOOYON&GOTO:JOOYON
cscript //nologo Bios\Bios.vbs | findstr /I "KRFTWY KRAFTWAY" >nul
%INL% SET MAN=KRAFTWAY&GOTO:KRAFTWAY
cscript //nologo Bios\Bios.vbs | findstr /I "K-Syst KSYSTEMS K-Systems" >nul
%INL% SET MAN=KSYSTEMS&GOTO:KSYSTEMS
cscript //nologo Bios\Bios.vbs | findstr /I "LANIX1 LANIX" >nul
%INL% SET MAN=LANIX&GOTO:LANIX
cscript //nologo Bios\Bios.vbs | findstr /I "LGE LGELGP LG" >nul
%INL% SET MAN=LG&GOTO:LG
cscript //nologo Bios\Bios.vbs | findstr /I "LENOVO" >nul
%INL% SET MAN=LENOVO&GOTO:LENOVO
cscript //nologo Bios\Bios.vbs | findstr /I "MEDION MEDIONPC MEDIONNB" >nul
%INL% SET MAN=MEDION&GOTO:MEDION
cscript //nologo Bios\Bios.vbs | findstr /I "MSI_NB MSI MSI_PC MSI-2831-MS MSI-PenNote" >nul
%INL% SET MAN=MSI&GOTO:MSI
cscript //nologo Bios\Bios.vbs | findstr /I "NEC NECC1 NECC_S NECCAP NECc_ NEC-PC NEC_Product" >nul
%INL% SET MAN=NEC&GOTO:NEC
cscript //nologo Bios\Bios.vbs | findstr /I "NOKIA" >nul
%INL% SET MAN=NOKIA&GOTO:NOKIA
cscript //nologo Bios\Bios.vbs | findstr /I "OLIPRO OLIDATA" >nul
%INL% SET MAN=OLIDATA&GOTO:OLIDATA
cscript //nologo Bios\Bios.vbs | findstr /I "PACKARD BELL PACKARD-BELL" >nul
%INL% SET MAN=PBELL&GOTO:ACER
cscript //nologo Bios\Bios.vbs | findstr /I "MATBIO Panasonic" >nul
%INL% SET MAN=PANASONIC&GOTO:PANASONIC
cscript //nologo Bios\Bios.vbs | findstr /I "QUANMX QUANMAX" >nul
%INL% SET MAN=QUANMAX&GOTO:QUANMAX
cscript //nologo Bios\Bios.vbs | findstr /I "SECCSD SAMSUNG SAMSUNGPC $SAMSUNGPC" >nul
%INL% SET MAN=SAMSUNG&GOTO:SAMSUNG
cscript //nologo Bios\Bios.vbs | findstr /I "stinfo" >nul
%INL% SET MAN=SEMP&GOTO:SEMP
cscript //nologo Bios\Bios.vbs | findstr /I "Sony" >nul
%INL% SET MAN=SONY&GOTO:SONY
cscript //nologo Bios\Bios.vbs | findstr /I "synnex" >nul
%INL% SET MAN=SYNNEX&GOTO:SYNNEX
cscript //nologo Bios\Bios.vbs | findstr /I "SYSMAX SYSTEMAX" >nul
%INL% SET MAN=SYSTEMAX&GOTO:SYSTEMAX
cscript //nologo Bios\Bios.vbs | findstr /I "TOSASU" >nul
%INL% SET MAN=TOSA&GOTO:TOSHIBA
cscript //nologo Bios\Bios.vbs | findstr /I "TOSCPL" >nul
%INL% SET MAN=TOSC&GOTO:TOSHIBA
cscript //nologo Bios\Bios.vbs | findstr /I "TOSHIB" >nul
%INL% SET MAN=TOSHIBA&GOTO:TOSHIBA
cscript //nologo Bios\Bios.vbs | findstr /I "TOSINV" >nul
%INL% SET MAN=TOSI&GOTO:TOSHIBA
cscript //nologo Bios\Bios.vbs | findstr /I "TOSQCI" >nul
%INL% SET MAN=TOSQ&GOTO:TOSHIBA
cscript //nologo Bios\Bios.vbs | findstr /I "TOSHIBA" >nul
%INL% SET MAN=TOSHIBA&GOTO:TOSHIBA
cscript //nologo Bios\Bios.vbs | findstr /I "THTFPC TONGFANG Tsing TSINGHUA" >nul
%INL% SET MAN=TONGFANG&GOTO:TONGFANG
cscript //nologo Bios\Bios.vbs | findstr /I "TRIGEM" >nul
%INL% SET MAN=TRIGEM&GOTO:TRIGEM
cscript //nologo Bios\Bios.vbs | findstr /I "YUTC VILIV" >nul
%INL% SET MAN=VILIV&GOTO:VILIV
cscript //nologo Bios\Bios.vbs | findstr /I "VSCAIO VIEWSONIC ViewSonic-PC ViewSonic-Notebook ViewSonic-AIOpc ViewSonic-Desktop" >nul
%INL% SET MAN=VSONIC&GOTO:VSONIC
cscript //nologo Bios\Bios.vbs | findstr /I "WORTMA wortmann" >nul
%INL% SET MAN=WORTMANN&GOTO:WORTMANN

::final checks::
cscript //nologo Bios\Bios.vbs | findstr /I "ACRSYS" >nul
%INL% SET MAN=ACER&GOTO:ACER
cscript //nologo Bios\Bios.vbs | findstr /I "HPQOEM" >nul
%INL% SET MAN=HP&GOTO:HP
cscript //nologo Bios\Bios.vbs | findstr /I "HP" >nul
%INL% SET MAN=HPPRO&GOTO:HP
cscript //nologo Bios\Bios.vbs | findstr /I "IBM" >nul
%INL% SET MAN=IBM&GOTO:LENOVO

::vmware::
WMIC BASEBOARD | findstr /I "VMWARE" >nul
%INL% SET MAN=VMWARE&GOTO:DEFAULT
WMIC BIOS | findstr /I "VMWARE" >nul
%INL% SET MAN=VMWARE&GOTO:DEFAULT
WMIC COMPUTERSYSTEM | findstr /I "VMWARE" >nul
%INL% SET MAN=VMWARE&GOTO:DEFAULT
WMIC CSPRODUCT | findstr /I "VMWARE" >nul
%INL% SET MAN=VMWARE&GOTO:DEFAULT

::set default brand/serial; if manufacturer not matched::
SET MAN=DEFAULT&GOTO:DEFAULT

::Manufacturer OEM Serial No's will get called from this list::
:ACER
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:ADVENT
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=38JTJ-VBPFW-XFQDR-PJ794-8447M
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:ALIENWARE
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=V3Y2W-CMF9W-PGT9C-777KD-32W74
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=VQ3PY-VRX6D-CBG4J-8C6R2-TCVBD
GOTO:FINISH
:ASUS
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:AQUARIUS
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:BENQ
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:CASPER
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6PB94-MC2C6-4F37H-KTJ32-PF2PT
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:COMPAQ
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RH98C-M9PW4-6DHR7-X99PJ-3FGDB
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=DX8R9-BVCGB-PPKRR-8J7T4-TJHTH
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=4FG99-BC3HD-73CQT-WMF7J-3Q6C9
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=74T2M-DKDBC-788W3-H689G-6P6GT
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=MHFPT-8C8M2-V9488-FGM44-2C9T3
GOTO:FINISH
:DEALIN
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=6M78P-JJRQP-9C4RX-RPK7G-3VTH3
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=8YDX9-B7MMG-82XD9-V88G9-MR92T
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=6BJ27-DVBFF-VKQC8-7JPQP-TJKYY
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:DEFAULT
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:DELL
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=36Q3Y-BBT84-MGJ3H-FT7VD-FG72J
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=36T88-RT7C6-R38TQ-RV8M9-WWTCY
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=6RBBT-F8VPQ-QCPVQ-KHRB8-RMV82
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=32KD2-K9CTF-M3DJT-4J3WC-733WD
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=342DG-6YJR8-X92GV-V7DCV-P4K27
GOTO:FINISH
:ECS
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=BHP4B-MXP9G-RG7KQ-T8R84-CW3D3
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:EXPER
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=4FRH4-WQDGJ-M9HRY-K73D8-RGT3C
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:FOUNDER
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=7WGMV-QFYXX-64DCG-HQFWM-DWGKY
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:FSC
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=PMXH9-M23P9-QJJMB-2FWRC-7CDKP
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=8W3JQ-BP2HY-F47QX-6CQ94-2BKQB
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=C6MHH-TRRPT-74TDC-FHRMV-XB88W
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=PT9YK-BC2J9-WWYF9-R9DCR-QB9CK
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=9CW99-79BBF-D4M3X-9BK9M-4RPH9
GOTO:FINISH
:FUJITSU
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=PMXH9-M23P9-QJJMB-2FWRC-7CDKP
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=8W3JQ-BP2HY-F47QX-6CQ94-2BKQB
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=C6MHH-TRRPT-74TDC-FHRMV-XB88W
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=PT9YK-BC2J9-WWYF9-R9DCR-QB9CK
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=9CW99-79BBF-D4M3X-9BK9M-4RPH9
GOTO:FINISH
:GIGABYTE
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:GWALL
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:HAIER
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:HANNSPREE
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=BRFCY-XMXRV-28JHQ-F6D9B-BV73C
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:HASEE
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:HCL
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=39QDH-D7MHH-WDMTD-TM2R9-KM7DB
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2QTV2-3CMPP-FQBYK-GRD62-D7XMW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:HIGRADE
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:HP
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RH98C-M9PW4-6DHR7-X99PJ-3FGDB
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=DX8R9-BVCGB-PPKRR-8J7T4-TJHTH
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=4FG99-BC3HD-73CQT-WMF7J-3Q6C9
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=74T2M-DKDBC-788W3-H689G-6P6GT
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=MHFPT-8C8M2-V9488-FGM44-2C9T3
GOTO:FINISH
:HYRICAN
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:JOOYON
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:KRAFTWAY
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=32HPJ-4XRDR-424C8-DYQM9-GM768
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:KSYSTEMS
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=82P6X-KGH24-FCPXC-XQKC9-74KC8
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:LANIX
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:LENOVO
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=273P4-GQ8V6-97YYM-9YTHF-DC2VP
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=22MFQ-HDH7V-RBV79-QMVK9-PTMXQ
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=27GBM-Y4QQC-JKHXW-D9W83-FJQKD
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=237XB-GDJ7B-MV8MH-98QJM-24367
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=6K2KY-BFH24-PJW6W-9GK29-TMPWP
GOTO:FINISH
:LG
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=38GRR-KMG3D-BTP99-TC9G4-BBDJJ
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2QGXM-V9W9W-6Q7MR-64C4X-R26CV
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:MEDION
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2P2P9-CM3F8-FTV6P-PC7CX-8TFF7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:MSI
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=2W4DJ-JFFJV-DMCPP-2C3X8-883DP
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=2TY7W-H4DD4-MB62F-BD9C3-88TM6
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=4G3GR-J6JDJ-D96PV-T9B9D-M8X2Q
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:NEC
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:NOKIA
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=2XGHP-9TQK2-8CF28-BM2P2-8FRX8
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:OLIDATA
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=344HQ-3YHDT-C7VCT-BDPBV-4KTR3
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:PANASONIC
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:QUANMAX
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:SAMSUNG
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=PV9BD-YBRX6-CTMG6-CCMJY-X8XG7
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=2P6PB-G7YVY-W46VJ-BXJ36-PGGTG
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=CQBVJ-9J697-PWB9R-4K7W4-2BT4J
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=GMJQF-JC7VC-76HMH-M4RKY-V4HX6
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=49PB6-6BJ6Y-KHGCQ-7DDY6-TF7CD
GOTO:FINISH
:SEMP
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:SONY
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=32J2V-TGQCY-9QJXP-Q3FVT-X8BQ7
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=YV7QQ-RCXQ9-KTBHC-YX3FG-FKRW8
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=H4JWX-WHKWT-VGV87-C7XPK-CGKHQ
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=H9M26-6BXJP-XXFCY-7BR4V-24X8J
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=YJJYR-666KV-8T4YH-KM9TB-4PY2W
GOTO:FINISH
:SYNNEX
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:SYSTEMAX
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=VQB3X-Q3KP8-WJ2H8-R6B6D-7QJB7
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:TONGFANG
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=9DBMT-GXRWM-6Q9Y3-WMYM8-FJCBW
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:TOSHIBA
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=TGBKB-9KBGJ-3Y3J6-K8M2F-J2HJQ
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=9H4FH-VD69Y-TGBD2-4PM4K-DRMMH
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=6B88K-KCCWY-4F8HK-M4P73-W8DQG
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2V8P2-QKJWM-4THM3-74PDB-4P2KH
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:TRIGEM
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:VILIV
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=7W842-2HCPJ-BC3MJ-B79K6-TD2HQ
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=2WCJK-R8B4Y-CWRF2-TRJKB-PV9HW
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH
:VSONIC
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=RDJXR-3M32B-FJT32-QMPGB-GCFF6
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=MB4HF-2Q8V3-W88WR-K7287-2H4CP
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=C23T3-9F2T2-FPWBM-XYMW2-272J9
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=YKHFT-KW986-GK4PY-FDWYH-7TP9F
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=FJGCP-4DFJD-GJY49-VJBQ7-HYRR2
GOTO:FINISH
:WORTMANN
%RQR% | findstr /I "STARTER"      && %INL% SET PIDKEY=6K6WB-X73TD-KG794-FJYHG-YCJVG
%RQR% | findstr /I "HOMEBASIC"    && %INL% SET PIDKEY=89G97-VYHYT-Y6G8H-PJXV6-77GQM
%RQR% | findstr /I "HOMEPREMIUM"  && %INL% SET PIDKEY=2QDBX-9T8HR-2QWT6-HCQXJ-9YQTR
%RQR% | findstr /I "PROFESSIONAL" && %INL% SET PIDKEY=6JKVQ-WJTWW-JVPRB-77TGD-2DV7M
%RQR% | findstr /I "ULTIMATE"     && %INL% SET PIDKEY=2Y4WT-DHTBF-Q6MMK-KYK6X-VKM6G
GOTO:FINISH

:FINISH
cd /d %ScriptPath%

:key
echo %MAN% OEM Key Installing
echo Please wait...
echo.
cscript //nologo "%Windir%\System32\slmgr.vbs" -dlv >check
find /i "OEM_SLP" >nul check && goto:certs
cscript //nologo %windir%\System32\slmgr.vbs -ipk %PIDKEY% >nul

:certs
if exist Certificates\%MAN%.xrm-ms echo %MAN% OEMCert.xrm-ms Installing && echo Please wait... && echo.
if exist Certificates\%MAN%.xrm-ms cscript //nologo %windir%\System32\slmgr.vbs -ilc Certificates\%MAN%.xrm-ms >nul

::Activation Check::
WMIC /NAMESPACE:\\root\CIMV2 PATH SoftwareLicensingProduct WHERE LicenseStatus=1 GET LicenseStatus | findstr "1" > nul
IF ERRORLEVEL 1 GOTO:FOEM
GOTO:END

:FOEM
echo Pirate Activation
echo Please wait...
echo.
ping 127.0.0.1 -n 3 >nul
cd /d %ScriptPath%
cd /d Pirate 
call Install.vbs
EXIT

:END
EXIT /B